---
name: PHP CS Fixer

on:
  - workflow_call
  - pull_request
  - push

jobs:
  php_cs_fixer:
    name: PHP CS Fixer

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"
          coverage: none

      - name: Update dependencies with composer
        run: composer update --no-interaction --ansi --no-progress

      - name: Install php-cs-fixer with composer
        run: composer bin php-cs-fixer update --no-interaction --ansi --no-progress

      - name: Run php-cs-fixer
        run: vendor/bin/phptailors-workflows run:php-cs-fixer
