---
name: Psalm

on:
  - workflow_call
  - pull_request
  - push

jobs:
  psalm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
          - "8.5"

    name: PHP-${{ matrix.php-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - run: composer --version

      - name: Update dependencies with composer
        run: composer update --no-interaction --ansi --no-progress

      - name: Install psalm with composer
        run: composer bin psalm update --no-interaction --ansi --no-progress

      - if: ${{ github.event_name == 'workflow_call' }}
        name: Run vimeo/psalm
        run: vendor/bin/phptailors-workflows run:psalm

      - if: ${{ github.event_name != 'workflow_call' }}
        name: Run vimeo/psalm
        run: php bin/phptailors-workflows run:psalm
